### PR TITLE
nispor: delete ip addr not in desired state

### LINKED ISSUE #2893: Change IP using kernel only does not work
## Describe the bug
Changing the IP address of a veth interface inside a Docker container using kernel-only mode fails. The new IP is added, the old IP is not removed despite `allow-extra-address: false` set.

## Nmstate version
- Version 2.2.44

## NetworkManager version
n/a (kernel only)

## Platform
- Platform:  Fedore 42 docker container, Host ubuntu 24.04

## How reproducible
- 100%

## Steps to Reproduce

```
➜ hex ~/Code/cadami/stachus/stachus-core (2335-update-evaluationkit-readme) ✗ % docker run -it --rm --cap-add=net_admin fedora:latest
[root@0e25b07f1aab /]# dnf install -qy nmstate iproute
Package                                                     Arch           Version                                                      Repository                            Size
Installing:
 iproute                                                    x86_64         6.12.0-3.fc42                                                fedora                             2.1 MiB
 nmstate                                                    x86_64         2.2.44-1.fc42                                                updates                           12.4 MiB
Installing dependencies:
 libbpf                                                     x86_64         2:1.5.0-2.fc42                                               fedora                           418.4 KiB
 libmnl                                                     x86_64         1.0.5-7.fc42                                                 fedora                            55.1 KiB
 psmisc                                                     x86_64         23.7-5.fc42                                                  fedora                           829.7 KiB

Transaction Summary:
 Installing:         5 packages

[1/7] Verify package files                                                                                                                100% | 357.0   B/s |   5.0   B |  00m00s
[2/7] Prepare transaction                                                                                                                 100% | 500.0   B/s |   5.0   B |  00m00s
[3/7] Installing psmisc-0:23.7-5.fc42.x86_64                                                                                              100% |  31.9 MiB/s | 848.2 KiB |  00m00s
[4/7] Installing libmnl-0:1.0.5-7.fc42.x86_64                                                                                             100% |  11.0 MiB/s |  56.4 KiB |  00m00s
[5/7] Installing libbpf-2:1.5.0-2.fc42.x86_64                                                                                             100% | 136.5 MiB/s | 419.3 KiB |  00m00s
[6/7] Installing iproute-0:6.12.0-3.fc42.x86_64                                                                                           100% |  54.1 MiB/s |   2.1 MiB |  00m00s
[7/7] Installing nmstate-0:2.2.44-1.fc42.x86_64                                                                                           100% | 122.1 MiB/s |  12.5 MiB |  00m00s
[root@0e25b07f1aab /]# ip a && ip r
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
2: eth0@if124: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 8a:af:61:8a:cf:80 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.254.0.4/16 brd 10.254.255.255 scope global eth0
       valid_lft forever preferred_lft forever
default via 10.254.0.1 dev eth0 
10.254.0.0/16 dev eth0 proto kernel scope link src 10.254.0.4 
[root@0e25b07f1aab /]# cat >5.yaml <<EOF
> route-rules:
  config: []
routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-interface: eth0
    next-hop-address: 10.254.0.1
    table-id: 254
interfaces:
- name: eth0
  type: veth
  state: up
  ipv4:
    enabled: true
    address:
    - ip: 10.254.0.5
      prefix-length: 16
    allow-extra-address: false
  ipv6:
    enabled: false
  mptcp:
    address-flags: []
EOF
[root@0e25b07f1aab /]# nmstatectl apply -k 5.yaml 
[2025-04-30T22:14:44Z INFO  nmstatectl] Nmstate version: 2.2.44
[2025-04-30T22:14:44Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth0.interface.ipv4.address desire '[{"ip":"10.254.0.5","prefix-length":16}]', current '[{"ip":"10.254.0.4","prefix-length":16},{"ip":"10.254.0.5","prefix-length":16}]'
[2025-04-30T22:14:45Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth0.interface.ipv4.address desire '[{"ip":"10.254.0.5","prefix-length":16}]', current '[{"ip":"10.254.0.4","prefix-length":16},{"ip":"10.254.0.5","prefix-length":16}]'
[2025-04-30T22:14:46Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth0.interface.ipv4.address desire '[{"ip":"10.254.0.5","prefix-length":16}]', current '[{"ip":"10.254.0.4","prefix-length":16},{"ip":"10.254.0.5","prefix-length":16}]'
[2025-04-30T22:14:47Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth0.interface.ipv4.address desire '[{"ip":"10.254.0.5","prefix-length":16}]', current '[{"ip":"10.254.0.4","prefix-length":16},{"ip":"10.254.0.5","prefix-length":16}]'
NmstateError: VerificationError: Verification failure: eth0.interface.ipv4.address desire '[{"ip":"10.254.0.5","prefix-length":16}]', current '[{"ip":"10.254.0.4","prefix-length":16},{"ip":"10.254.0.5","prefix-length":16}]'
```

## Nmstate output
see above

### Additional context
none

### PR DESCRIPTION
**Pull request by rajeshrah22**
Previously, new IP addr on same interface was being appended to addresses list instead of being updated.

This solution asks nispor to delete ip addresses in the current state not contained in the desired state.

Resolves: https://issues.redhat.com/browse/RHEL-54544
Resolves: #2893

### CODE REVIEW

**Comment by rajeshrah22** [comment]
Little reproducer script: https://gist.github.com/rajeshrah22/405c64245668a5c2d22abff497394388

**Comment by rajeshrah22** [comment]
This issue appears to require an integration test.
I'm thinking:
- Create Interface with old IP.
- Apply new IP to interface.
- Check that the interface only has new IP afterward.

Maybe this can be done with unit test. I will need to look into it.

I will do this when I get time.

**Comment by rajeshrah22** [comment]
I implemented the creation of *delete old IP* and *create new IP* configurations in the nmstate nispor integration code. 

I was considering whether nispor needed changing; however, with the reasoning that nispor is a library that does little and is only a small abstraction over rust-netlink, I decided it shouldn't handle this.

From my understanding, Nispor almost directly maps Nispor conf to netlink messages.

File: rust/src/lib/nispor/apply.rs [hunk 1]
```diff
@@ -88,41 +91,57 @@ fn nmstate_iface_type_to_np(
 }
 
 fn nmstate_iface_to_np(
-    nms_iface: &Interface,
+    nms_des_iface: &Interface,
+    nms_cur_iface: Option<&Interface>,
 ) -> Result<nispor::IfaceConf, NmstateError> {
```
Comment (ihuguet) [inline rust/src/lib/nispor/apply.rs]: Instead of passing 2 arguments, better change it to accept only &MergedInterface. Then, inside you can use the iface.for_apply everywhere, maintaining the old behaviour except when calling to nmstate_ipvX_to_np where you can pass the entire &MergedInterface.

File: rust/src/lib/nispor/ip.rs [hunk 2]
```diff
@@ -137,11 +137,12 @@ pub(crate) fn np_ipv6_to_nmstate(
 }
 
 pub(crate) fn nmstate_ipv4_to_np(
-    nms_ipv4: Option<&InterfaceIpv4>,
+    nms_des_ipv4: Option<&InterfaceIpv4>,
+    nms_cur_ipv4: Option<&InterfaceIpv4>,
 ) -> nispor::IpConf {
```
Comment (ihuguet) [inline rust/src/lib/nispor/ip.rs]: Continuing with the previous comment, here accept only a &MergedInterface, then use the iface.for_apply for the parts of the function body that don't change, and compare iface.current with iface.merged to add the addresses to remove.

File: rust/src/lib/nispor/ip.rs [hunk 3]
```diff
@@ -150,15 +151,38 @@ pub(crate) fn nmstate_ipv4_to_np(
...
+        (nms_cur_ipv4, nms_des_ipv4)
+    {
+        for nms_addr in nms_cur_ipv4.addresses.as_deref().unwrap_or_default() {
+            if let Some(des_addresses) = nms_des_ipv4.addresses.as_ref() {
+                if !des_addresses
+                    .iter()
+                    .map(|addr| addr.ip)
+                    .collect::<Vec<_>>()
+                    .contains(&nms_addr.ip)
+                {
```
Comment (ihuguet) [inline rust/src/lib/nispor/ip.rs]: This is a bit inefficient because you iterate des_addresses many times, and allocating a Vec each time. Why not:
1. Create HashSet with addresses from iface.merged
2. Create HashSet with addresses from iface.current
3. Iterate `addr in cur_addresses.difference(merged_addresses)`, which are the addresses in current and not in merged.

**Review by ihuguet — CHANGES_REQUESTED** [review]
Good work overall

File: rust/src/lib/nispor/ip.rs (hunk 3 above)
Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs]:
```rs
 if let (Some(nms_cur_ipv4), Some(nms_des_ipv4)) = (
        &nms_merged_iface.current.as_ref().unwrap().base_iface().ipv4,
        &nms_merged_iface.merged.base_iface().ipv4,
    ) {
        let merged_addresses: HashSet<_> = nms_des_ipv4
            .addresses
            .as_deref()
            .unwrap_or_default()
            .iter()
            .collect();

        let cur_addresses: HashSet<_> = nms_cur_ipv4
            .addresses
            .as_deref()
            .unwrap_or_default()
            .iter()
            .collect();

        for nms_addr in cur_addresses.difference(&merged_addresses) {
            np_ip_conf.addresses.push({
                let mut ip_conf = nispor::IpAddrConf::default();
                ip_conf.address = nms_addr.ip.to_string();
                ip_conf.prefix_len = nms_addr.prefix_length;
                ip_conf.remove = true;
                ip_conf
            });
        }
    }
```
This causes:

```
rahulrajesh@rahulvm:~/projects/nmstate$ cd rust; cargo check; cd ..
    Checking nmstate v2.2.49 (/home/rahulrajesh/projects/nmstate/rust/src/lib)
error[E0277]: the trait bound `InterfaceIpAddr: Hash` is not satisfied
    --> src/lib/nispor/ip.rs:162:14
     |
162  |             .collect();
     |              ^^^^^^^ the trait `Hash` is not implemented for `InterfaceIpAddr`
     |
     = help: the trait `FromIterator<T>` is implemented for `HashSet<T, S>`
     = note: required for `&InterfaceIpAddr` to implement `Hash`
     = note: required for `HashSet<&InterfaceIpAddr>` to implement `FromIterator<&InterfaceIpAddr>`
note: required by a bound in `collect`
    --> /home/rahulrajesh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1972:19
     |
1972 |     fn collect<B: FromIterator<Self::Item>>(self) -> B
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Iterator::collect`

error[E0277]: the trait bound `InterfaceIpAddr: Hash` is not satisfied
    --> src/lib/nispor/ip.rs:169:14
     |
169  |             .collect();
     |              ^^^^^^^ the trait `Hash` is not implemented for `InterfaceIpAddr`
     |
     = help: the trait `FromIterator<T>` is implemented for `HashSet<T, S>`
     = note: required for `&InterfaceIpAddr` to implement `Hash`
     = note: required for `HashSet<&InterfaceIpAddr>` to implement `FromIterator<&InterfaceIpAddr>`
note: required by a bound in `collect`
    --> /home/rahulrajesh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1972:19
     |
1972 |     fn collect<B: FromIterator<Self::Item>>(self) -> B
     |                   ^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Iterator::collect`

error[E0599]: the method `difference` exists for struct `HashSet<&InterfaceIpAddr>`, but its trait bounds were not satisfied
   --> src/lib/nispor/ip.rs:171:39
    |
171 |         for nms_addr in cur_addresses.difference(&merged_addresses) {
    |                                       ^^^^^^^^^^ method cannot be called on `HashSet<&InterfaceIpAddr>` due to unsatisfied trait bounds
    |
   ::: src/lib/ip.rs:854:1
    |
854 | pub struct InterfaceIpAddr {
    | -------------------------- doesn't satisfy `InterfaceIpAddr: Hash`
    |
    = note: the following trait bounds were not satisfied:
            `InterfaceIpAddr: Hash`
            which is required by `&InterfaceIpAddr: Hash`
help: consider annotating `InterfaceIpAddr` with `#[derive(Hash)]`
   --> src/lib/ip.rs:854:1
    |
854 + #[derive(Hash)]
855 | pub struct InterfaceIpAddr {
    |
```

I don't know how the `#[derive(Hash)]` works so I will have to look into it.
I like how the rust :crab: compiler can suggest fixes. I wonder how they do that :thinking:

Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs]: Ok, my hashset commit is breaking things.

Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs]: I think I fixed it ...

**Review by cathay4t — CHANGES_REQUESTED** [review]
1. HashSet will not preserve IP address order, but the order of IP address matters.
2. MPTCP flags is not supported by nispor yet, so it make no sense to `derive Hash` on the whole `InterfaceIpAddr`.

**Comment by cathay4t** [comment]
Please also squash the patches into single one unless the patch is too big for review.

**Comment by rajeshrah22** [comment]
> 1. HashSet will not preserve IP address order, but the order of IP address matters.
> 
>     2. MPTCP flags is not supported by nispor yet, so it make no sense to `derive Hash` on the whole `InterfaceIpAddr`.

So, a Vector would probably work just fine? Hashset wouldn't make that much of a difference in performance for such small number of elements anyways.
A vector would preserve the order.

File: rust/src/lib/nispor/apply.rs [hunk 4]
```diff
@@ -88,41 +88,45 @@ fn nmstate_iface_type_to_np(
 }
 
 fn nmstate_iface_to_np(
-    nms_iface: &Interface,
+    nms_merged_iface: &MergedInterface,
 ) -> Result<nispor::IfaceConf, NmstateError> {
     let mut np_iface = nispor::IfaceConf::default();
+    let nms_for_apply = nms_merged_iface.for_apply.as_ref().unwrap();
```
Comment (cathay4t) [inline rust/src/lib/nispor/apply.rs]: Unwrap here is dangerous. In the future, developer might forgot he/she can only pass `MergedInterface` with non-empty `for_apply`.

Please raise `BUG` error instead of panic.

File: rust/src/lib/nispor/apply.rs [hunk 5]
```diff
@@ -88,41 +88,45 @@ fn nmstate_iface_type_to_np(
...
 
-    let mut np_iface_type = nmstate_iface_type_to_np(&nms_iface.iface_type());
+    let mut np_iface_type =
+        nmstate_iface_type_to_np(&nms_for_apply.iface_type());
```
Comment (cathay4t) [inline rust/src/lib/nispor/apply.rs]: If you name it as `nms_iface` at first place, you don't need to change follow up lines.

File: rust/src/lib/nispor/apply.rs [hunk 6]
```diff
@@ -88,41 +88,45 @@ fn nmstate_iface_type_to_np(
...
+    if nms_for_apply.is_absent() {
         np_iface.state = nispor::IfaceState::Absent;
         return Ok(np_iface);
     }
 
     np_iface.state = nispor::IfaceState::Up;
 
-    let base_iface = &nms_iface.base_iface();
-    if let Some(ctrl_name) = &base_iface.controller {
+    let des_base_iface = &nms_for_apply.base_iface();
```
Comment (cathay4t) [inline rust/src/lib/nispor/apply.rs]: Try not rename variable, these changes only confuse the review.

File: rust/src/lib/nispor/apply.rs [hunk 7]
```diff
@@ -154,8 +158,9 @@ async fn delete_ifaces(
                 deleted_veths.push(peer_name);
             }
         }
-        if let Some(apply_iface) = iface.for_apply.as_ref() {
-            np_ifaces.push(nmstate_iface_to_np(apply_iface)?);
+
+        if iface.for_verify.as_ref().is_some() {
```
Comment (cathay4t) [inline rust/src/lib/nispor/apply.rs]: Change `for_apply` to `for_verify`?

**Review by cathay4t — CHANGES_REQUESTED** [review]

**Comment by cathay4t** [comment]
Please do not split code change and test, use single patch please.

File: rust/src/lib/nispor/apply.rs (hunk 7 above)
Comment (rajeshrah22) [reply rust/src/lib/nispor/apply.rs]: Mistake. I changed back to for_apply.

File: rust/src/lib/nispor/apply.rs (hunk 6 above)
Comment (rajeshrah22) [reply rust/src/lib/nispor/apply.rs]: Sure, changed it back.

**Review by cathay4t — APPROVED** [review]

File: rust/src/lib/nispor/ip.rs [hunk 8]
```diff
@@ -150,15 +150,44 @@ pub(crate) fn nmstate_ipv4_to_np(
...
+                if !des_ips.contains(&nms_addr.ip) {
+                    np_ip_conf.addresses.push({
+                        let mut ip_conf = nispor::IpAddrConf::default();
+                        ip_conf.address = nms_addr.ip.to_string();
+                        ip_conf.prefix_len = nms_addr.prefix_length;
+                        ip_conf.remove = true;
+                        ip_conf
+                    });
+                }
+            }
```
Comment (ihuguet) [inline rust/src/lib/nispor/ip.rs]: IMO you should compare entire InterfaceIpAddr here. Like:
```
let des_ips: Vec<_> = nms_des_ipv4.addresses.as_deref().unwrap_or_default();
for ... {
    if !des_ips.contains(&nms_addr) { ... }
}
```

Otherwise, if the current state contains `192.168.1.10/32 and the desired state contains 192.168.1.10/24 the old one won't be removed. Same for IPv6.

Comment (ihuguet) [reply rust/src/lib/nispor/ip.rs]: Actually, after doing the change, that case may deserve a test to avoid a regression in the future.

**Comment by rajeshrah22** [comment]
Does the order in which addresses are added into nispor::IpConf.address matter? More specifically, would adding new IP (remove = false) before deleting IP (remove = true) make a difference?

File: rust/src/lib/nispor/ip.rs (hunk 8 above)
Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs]: Added test case.

File: rust/src/lib/nispor/ip.rs [hunk 9]
```diff
@@ -154,11 +197,42 @@ pub(crate) fn nmstate_ipv4_to_np(
...
+        }
+    }
+
+    // Add new ip address entries after deleting
+    if let Some(nms_des_ipv6) = &nms_merged_iface.merged.base_iface().ipv6 {
+        for nms_addr in nms_des_ipv6.addresses.as_deref().unwrap_or_default() {
```
Comment (rajeshrah22) [inline rust/src/lib/nispor/ip.rs:235]: The order here made a difference. If I added IP address first before deleting, I got verification error where current state has ipv6 disabled and desired state has ipv6 enabled.

Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs:235]: Any idea why this might be the case? I did not have time to look into it.

Comment (ihuguet) [reply rust/src/lib/nispor/ip.rs:235]: No, sorry

**Review by ihuguet — APPROVED** [review]

File: rust/src/lib/nispor/ip.rs (hunk 9 above)
Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs:235]: https://gist.github.com/rajeshrah22/7cacbc2422745085e3afbe41324ba5ec
```bash
read -r -d '' ETH1 <<EOF
interfaces: 
  - name: eth1
    type: ethernet
    state: up
    ipv4:
      address: 
      - ip: 192.0.2.1
        prefix-length: 24
      dhcp: false
      enabled: true
    ipv6:
      address: 
      - ip: 2001:db8:1::1
        prefix-length: 64
      dhcp: false
      enabled: true
      autoconf: false
EOF

read -r -d '' ETH1_CHANGED_IP <<EOF
interfaces: 
  - name: eth1
    type: ethernet
    state: up
    ipv4:
      address: 
      - ip: 192.0.2.1
        prefix-length: 12
      dhcp: false
      enabled: true
    ipv6:
      address: 
      - ip: 2001:db8:1::1
        prefix-length: 32
      dhcp: false
      enabled: true
      autoconf: false
EOF

setup_eth1() {
  sudo ip link add eth1 type veth peer eth1_p
  sudo ip link set eth1 up
  sudo ip link set eth1_p up
}

cleanup_eth1() {
  sudo ip link delete eth1
}

main() {
  sudo systemctl stop NetworkManager
  setup_eth1
  echo "$ETH1" | sudo ./rust/target/debug/nmstatectl apply -k -
  echo "sleeping 1 second ..."
  sleep 1
  echo "$ETH1_CHANGED_IP" | sudo ./rust/target/debug/nmstatectl apply -k -
  echo "sleeping 1 second ..."
  sleep 1
  ip a show eth1
  ./rust/target/debug/nmstatectl show eth1 -k
  cleanup_eth1
  sudo systemctl start NetworkManager
}

main
```
Shell code snippet with states being applied ^

Result when adding new IP address conf before deleting old:
```
[2025-08-14T01:58:22Z INFO  nmstatectl] Nmstate version: 2.2.50
[/home/rahulrajesh/projects/nispor/src/lib/net_conf.rs:27:13] ifaces = []
[/home/rahulrajesh/projects/nispor/src/lib/net_conf.rs:27:13] ifaces = [
    IfaceConf {
        name: "eth1",
        state: Up,
        iface_type: Some(
            Ethernet,
        ),
        controller: None,
        ipv4: Some(
            IpConf {
                addresses: [
                    IpAddrConf {
                        remove: false,
                        address: "192.0.2.1",
                        prefix_len: 12,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                    IpAddrConf {
                        remove: true,
                        address: "192.0.2.1",
                        prefix_len: 24,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                ],
            },
        ),
        ipv6: Some(
            IpConf {
                addresses: [
                    IpAddrConf {
                        remove: false,                                    < ------------- add new IP
                        address: "2001:db8:1::1",
                        prefix_len: 32,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                    IpAddrConf {
                        remove: true,                                       < ------------- delete old IP
                        address: "2001:db8:1::1",
                        prefix_len: 64,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                ],
            },
        ),
        mac_address: None,
        veth: None,
        bridge: None,
        vlan: None,
        bond: None,
    },
]
[2025-08-14T01:58:23Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
[2025-08-14T01:58:24Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
[2025-08-14T01:58:25Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
[2025-08-14T01:58:26Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
NmstateError: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'

```

Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs:235]: If old addresses are deleted first before adding new:
```
[2025-08-14T01:44:08Z INFO  nmstatectl] Nmstate version: 2.2.50
[/home/rahulrajesh/projects/nispor/src/lib/net_conf.rs:27:13] ifaces = []
[/home/rahulrajesh/projects/nispor/src/lib/net_conf.rs:27:13] ifaces = [
    IfaceConf {
        name: "eth1",
        state: Up,
        iface_type: Some(
            Ethernet,
        ),
        controller: None,
        ipv4: Some(
            IpConf {
                addresses: [
                    IpAddrConf {
                        remove: true,
                        address: "192.0.2.1",
                        prefix_len: 24,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                    IpAddrConf {
                        remove: false,
                        address: "192.0.2.1",
                        prefix_len: 12,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                ],
            },
        ),
        ipv6: Some(
            IpConf {
                addresses: [
                    IpAddrConf {
                        remove: true,                           < ----------- delete old IP address
                        address: "2001:db8:1::1",
                        prefix_len: 64,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                    IpAddrConf {
                        remove: false,                          < ---------------- new IP address
                        address: "2001:db8:1::1",
                        prefix_len: 32,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                ],
            },
        ),
        mac_address: None,
        veth: None,
        bridge: None,
        vlan: None,
        bond: None,
    },
]
route-rules: {}
routes: {}
interfaces:
- name: eth1
  type: ethernet
  state: up
  ipv4:
    dhcp: false
    address:
    - ip: 192.0.2.1
      prefix-length: 12
  ipv6:
    dhcp: false
    autoconf: false
    address:
    - ip: 2001:db8:1::1
      prefix-length: 32
ovn: {}

```

Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs:235]: This has never caused a problem for ipv4.

Comment (ihuguet) [reply rust/src/lib/nispor/ip.rs:235]: Does this happens if the addresses are completely different? As the example has the same address but with different prefix, probably it's related to how the kernel treats IPv6 routes. Many times it merges routes automatically as ECMP routes. FYI: in the kernel IPv4 and IPv6 are completely different stacks that behaves quite differently in multiple things.
Add `--no-verify` to the 2nd nmstate call and check the output of `ip -d -6 a` and `ip -d -6 r` to see what has happened.

Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs:235]: Good to know that ipv4 and ipv6 have completely different implementations in the kernel. Since I have time, I want to figure out exactly why this is happening.

No, this has not happened for completely different addresses.

Ok, will try `--no-verify`.

Comment (rajeshrah22) [reply rust/src/lib/nispor/ip.rs:235]: Without `--no-verify`
```
]
[2025-08-14T14:41:38Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
[2025-08-14T14:41:39Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
[2025-08-14T14:41:40Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
[2025-08-14T14:41:41Z INFO  nmstate::query_apply::net_state] Retrying on: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
NmstateError: VerificationError: Verification failure: eth1.interface.ipv6.enabled desire 'true', current 'false'
sleeping 1 second ...
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    link/ether 52:54:00:00:91:66
    inet6 fe80::5054:ff:fe00:9166/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
7: eth1_p@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    link/ether ca:65:a8:48:85:7f
    inet6 fe80::c865:a8ff:fe48:857f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
unicast ::1 dev lo proto kernel scope global metric 30 pref medium
unicast fe80::/64 dev eth1_p proto kernel scope global metric 256 pref medium
unicast fe80::/64 dev enp1s0 proto kernel scope global metric 1024 pref medium
[2025-08-14T14:41:43Z INFO  nmstatectl] Nmstate version: 2.2.50
interfaces:
- name: eth1
  type: veth
  state: up
  mac-address: 16:A8:A6:3C:8D:11
  mtu: 1500
  min-mtu: 68
  max-mtu: 65535
  ipv4:
    enabled: true
    address:
    - ip: 192.0.2.1
      prefix-length: 12
  ipv6:
    enabled: false
  mptcp:
    address-flags: []
  accept-all-mac-addresses: false
  ethtool:
    feature:
      highdma: true
      rx-checksum: true
      rx-gro: false
      rx-gro-list: false
      rx-udp-gro-forwarding: false
      rx-vlan-hw-parse: true
      rx-vlan-stag-hw-parse: true
      tx-checksum-ip-generic: true
      tx-checksum-sctp: true
      tx-generic-segmentation: true
      tx-gre-csum-segmentation: true
      tx-gre-segmentation: true
      tx-gso-list: true
      tx-ipxip4-segmentation: true
      tx-ipxip6-segmentation: true
      tx-nocache-copy: false
      tx-scatter-gather-fraglist: true
      tx-sctp-segmentation: true
      tx-tcp-ecn-segmentation: true
      tx-tcp-mangleid-segmentation: true
      tx-tcp-segmentation: true
      tx-tcp6-segmentation: true
      tx-udp-segmentation: true
      tx-udp_tnl-csum-segmentation: true
      tx-udp_tnl-segmentation: true
      tx-vlan-hw-insert: true
      tx-vlan-stag-hw-insert: true
  veth:
    peer: eth1_p
```

With `--no-verify`:

```
sleeping 1 second ...
[2025-08-14T14:44:43Z INFO  nmstatectl] Nmstate version: 2.2.50
[/home/rahulrajesh/projects/nispor/src/lib/net_conf.rs:27:13] ifaces = []
[/home/rahulrajesh/projects/nispor/src/lib/net_conf.rs:27:13] ifaces = [
    IfaceConf {
        name: "eth1",
        state: Up,
        iface_type: Some(
            Ethernet,
        ),
        controller: None,
        ipv4: Some(
            IpConf {
                addresses: [
                    IpAddrConf {
                        remove: false,
                        address: "192.0.2.1",
                        prefix_len: 12,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                    IpAddrConf {
                        remove: true,
                        address: "192.0.2.1",
                        prefix_len: 24,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                ],
            },
        ),
        ipv6: Some(
            IpConf {
                addresses: [
                    IpAddrConf {
                        remove: false,
                        address: "2001:db8:1::1",
                        prefix_len: 32,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                    IpAddrConf {
                        remove: true,
                        address: "2001:db8:1::1",
                        prefix_len: 64,
                        valid_lft: "",
                        preferred_lft: "",
                    },
                ],
            },
        ),
        mac_address: None,
        veth: None,
        bridge: None,
        vlan: None,
        bond: None,
    },
]
route-rules: {}            < --------------- second configuration applies
routes: {}
interfaces:
- name: eth1
  type: ethernet
  state: up
  ipv4:
    dhcp: false
    address:
    - ip: 192.0.2.1
      prefix-length: 12
  ipv6:
    dhcp: false
    autoconf: false
    address:
    - ip: 2001:db8:1::1
      prefix-length: 32
ovn: {}

sleeping 1 second ...
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    link/ether 52:54:00:00:91:66
    inet6 fe80::5054:ff:fe00:9166/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
11: eth1_p@eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000    < ------------- Don't see main eth1, only eth1_p.
    link/ether ca:65:a8:48:85:7f
    inet6 fe80::c865:a8ff:fe48:857f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
unicast ::1 dev lo proto kernel scope global metric 30 pref medium
unicast fe80::/64 dev eth1_p proto kernel scope global metric 256 pref medium
unicast fe80::/64 dev enp1s0 proto kernel scope global metric 1024 pref medium
[2025-08-14T14:44:44Z INFO  nmstatectl] Nmstate version: 2.2.50
interfaces:
- name: eth1
  type: veth
  state: up
  mac-address: 16:A8:A6:3C:8D:11
  mtu: 1500
  min-mtu: 68
  max-mtu: 65535
  ipv4:
    enabled: true
    address:
    - ip: 192.0.2.1
      prefix-length: 12
  ipv6:
    enabled: false
  mptcp:
    address-flags: []
  accept-all-mac-addresses: false
  ethtool:
    feature:
      highdma: true
      rx-checksum: true
      rx-gro: false
      rx-gro-list: false
      rx-udp-gro-forwarding: false
      rx-vlan-hw-parse: true
      rx-vlan-stag-hw-parse: true
      tx-checksum-ip-generic: true
      tx-checksum-sctp: true
      tx-generic-segmentation: true
      tx-gre-csum-segmentation: true
      tx-gre-segmentation: true
      tx-gso-list: true
      tx-ipxip4-segmentation: true
      tx-ipxip6-segmentation: true
      tx-nocache-copy: false
      tx-scatter-gather-fraglist: true
      tx-sctp-segmentation: true
      tx-tcp-ecn-segmentation: true
      tx-tcp-mangleid-segmentation: true
      tx-tcp-segmentation: true
      tx-tcp6-segmentation: true
      tx-udp-segmentation: true
      tx-udp_tnl-csum-segmentation: true
      tx-udp_tnl-segmentation: true
      tx-vlan-hw-insert: true
      tx-vlan-stag-hw-insert: true
  veth:
    peer: eth1_p
```

Comment (cathay4t) [reply rust/src/lib/nispor/ip.rs:235]: nispor does not do smart ordering, it just execute on the order you requested.

So I think nmstate should remove IP address first.

**Review by cathay4t — APPROVED** [review]

**Comment by cathay4t** [comment]
We still have problem when applying

```yml
        name: lo
        type: loopback
        ipv4:
          enabled: true
          address:
          - ip: 127.0.0.2
            prefix-length: 32
          - ip: 127.0.0.1
            prefix-length: 8
        ipv6:
          enabled: true
          address:
          - ip: ::2
            prefix-length: 128
          - ip: ::1
            prefix-length: 128
```

This case, the index of IP address changed, so we should purge current ips. Anyway, I will create PR for this.

**Comment by rajeshrah22** [comment]
> We still have problem when applying
> 
> ```yaml
>         name: lo
>         type: loopback
>         ipv4:
>           enabled: true
>           address:
>           - ip: 127.0.0.2
>             prefix-length: 32
>           - ip: 127.0.0.1
>             prefix-length: 8
>         ipv6:
>           enabled: true
>           address:
>           - ip: ::2
>             prefix-length: 128
>           - ip: ::1
>             prefix-length: 128
> ```
> 
> This case, the index of IP address changed, so we should purge current ips. Anyway, I will create PR for this.

Sure, thanks.
